# Generated by Django 5.0.7 on 2024-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_hub_attributes_course_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="section",
            name="last_rmp_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
