# Generated by Django 5.0.7 on 2024-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_storedcourse_storedsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="end_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="start_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
