# Generated by Django 5.1.2 on 2025-03-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_fix_section_course_id"),
        ("courses", "0006_fix_section_fk"),
    ]

    operations = []
