# Generated by Django 5.1.2 on 2025-03-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_fix_course_relations"),
        ("courses", "0009_fix_schema_final"),
    ]

    operations = []
